apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  #namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: nginx2
    image: nginx
    securityContext:
      privileged: true
    volumeMounts:
      - name: rootfs
        mountPath: /rootfs
  volumes:
    - name: rootfs
      hostPath:
        path: /
