---
apiVersion: v1
kind: Service
metadata:
  name: vulnweb
  namespace: default
  labels:
    k8s-app: vulnweb
spec:
  #type: LoadBalancer
  ports:
  - port: 8000
    protocol: "TCP"
    targetPort: 8080
  selector:
    k8s-app: vulnweb

